<?php

return [
    'roles' => [
        'admin' => [
            'dashboard.view',
            'calendar.view',
            'general_fund.view',
            'trust_fund.view',
            'community_tax.view',
            'real_property_tax.view',
            'cash_tickets.view',
            'business_permits.view',
            'mto_permits.view',
            'rcd.view',
            'aco_dashboard.view',
            'income_target.view',
            'search_receipts.view',
            'search_receipts.edit',
            'reports.view',
            'reports.export',
            'settings.view',
            'users.manage',
        ],
        'treasurer' => [
            'dashboard.view',
            'calendar.view',
            'general_fund.view',
            'trust_fund.view',
            'community_tax.view',
            'rcd.view',
            'aco_dashboard.view',
            'income_target.view',
            'search_receipts.view',
            'search_receipts.edit',
            'reports.view',
            'reports.export',
            'settings.view',
        ],
        'cashier' => [
            'dashboard.view',
            'calendar.view',
            'rcd.view',
            'search_receipts.view',
            'reports.view',
            'settings.view',
        ],
        'collector' => [
            'calendar.view',
            'rcd.view',
            'settings.view',
        ],
        'viewer' => [
            'dashboard.view',
            'calendar.view',
            'income_target.view',
            'settings.view',
        ],
    ],
];
